### PR TITLE
[WIP] Nova 4 Support

### PR DESCRIPTION
**Pull request by Jubeki**
I am working on getting the package running on Nova 4. I already have some basic things implemented but there is still a lot todo. Therefor it may take me a while before it is even stable.

TODO:

- [x] Fix Styling
- [x] Add Dark Mode
- [ ] Get Tests running
- [ ] Tryout phase

Everybody is more than welcome to help.

Related #338 

If you find errors (design or functional) please report them as a comment in this PR with screenshots and what steps you did take to get them.

To try out these changes you can add the following to your composer.json
```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/Jubeki/nova-flexible-content"
        }
    ],
    "require": {
        "whitecube/nova-flexible-content": "dev-nova-4"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

### CODE REVIEW

**Comment by voidgraphics** [comment]
Thank you very much! As stated in the issue, I don't currently have a Nova 4 license so my contribution to this is limited, but let me know if there's anything I can do. 

Do you have anything in mind as far as getting some tests in place? I figure doing tests with Laravel Dusk on a separate repo with a sample project is probably the safest bet, like Nova itself does it, but it's rather impractical. I'm curious to know if anyone has other ideas. Unit tests would be a decent start but sadly would not cover much ground to ensure the actual field behaves correctly when inserted in a real Nova environment, imo.

**Comment by Jubeki** [comment]
For tests I have no plan yet. For now my goal is getting it to run and maybe find unexpected problems.

Everything seems to be working fine for now, but there may be issues which I just didn't account for. I will now try to fix some design issues and then take a look at the tests.

**Comment by Jubeki** [comment]
@voidgraphics how about this idea:
For now I will try to make this package work with nova 4 (without much test coverage, just to get it working for these folks who want to upgrade). The nova 4 support will not be a released but instead a dev branch like `dev-nova-4` in this repo.

Any issue which happens with Nova 4 can be reported in a special issue or in another repository for all nova packages in the namespace `whitecube`.
When I have time I will try to fix some of these issues and send in PR for them. This does not include feature requests, only bug reports because I also have limited time available. Or other people can also send in another PR.

If I have time I will maybe look into other nova packages to upgrade them, but for now I will try my best to get these nova packages running which I need for my projects.

**Comment by Jubeki** [comment]
So it would be like unofficial support for now and people with issues need to solve these themselves.

**Comment by voidgraphics** [comment]
Thanks to a generous sponsorship from @bashgeek we have now acquired a license for Nova 4. 

I will be able to give this PR a test and hopefully help get things in order over the week-end.

**Comment by Jubeki** [comment]
@voidgraphics Here some instructions for getting the build steps running:

After you have checked out the branch you need to run the following:
```bash
# Install Laravel Nova 4 Dependencies
composer update

# Install Nova Dependencies: https://github.com/laravel/nova-issues/issues/3856
cd vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install

# If you want Vue DevTools Support
npm run dev

# Install and Build Nova-Flexible-Content Assets
cd ../../..
npm install
npm run watch
```

**Comment by Jubeki** [comment]
So here a little update what is working currently (kind of a changelong)
- Updated Styling for Nova 4
    - Colors
    - Borders
    - Dark Mode
- Updated Icons
    - Use Heroicons instead of custom ones (delivered with nova)
- Functional Tests
    - Confirm Removal of FieldGroup
    - Details Page is showing correct results
    - Move Up and Down
    - Collapsing and Expanding
    - Saving
- Updated composer dependencies
    - Laravel Nova 4
    - Laravel Framework 8 and 9
    - PHP ^7.3 and ^8.0
- Updated npm dependencies
    - Vue 3
- Updated Build steps in `webpack.mix.js`

What still needs to be done/checked
- Search Menu (Currently not working, but also not documented)
     - Already installed `@vueform/multiselect`
     - Maybe consider using headlessui? (https://headlessui.dev/vue/combobox)
- Styling and functional issues full check (Probably with tryout phase)
- Tests

**Comment by voidgraphics** [comment]
From some quick testing, there are a few remaining styling problems. 

To combat some of those, I have reworked the design a little bit:

CleanShot 2022-04-08 at 23 17 18@2x

It seems like there is an issue with the markdown field not having enough room, at least on my 14" MBP. I don't think there is much we can do about it, except recommend using the `->stacked()` option to make the label go above the field instead of on the side, but that seems to have not work currently in Nova 4, for any field.

I will do more testing tomorrow/sunday and set up a few dusk tests on the other repo.

**Comment by Jubeki** [comment]
Well it would be possible to make GroupField itself stacked using the `FullWidthField` component which already exists. This would give all fields more room to breath.

**Comment by Jubeki** [comment]
I will mark this PR as ready for Review that you can merge it any time you want.

**Comment by chrisvasey** [comment]
Thank you both for your work on this, I am very excited to use it more and this package is one of my daily drivers for building in Nova 3.
I will drop a sponsor on the project now to assist towards another maintainer's licence if needed and check back to see if there is anything I can help with over the weekend once I have picked up my own licence.

**Comment by stepanenko3** [comment]
Method Whitecube\\NovaFlexibleContent\\Flexible::dependsOn does not exist.

and

dependsOn not working inside flexible

```
Flexible::make('Fields', 'fields')
    ->addLayout('Simple content section', 'wysiwyg', [
        Select::make('Purchase Type', 'type')
            ->options([
                'personal' => 'Personal',
                'gift' => 'Gift',
            ]),

        // Recipient field configuration is customized based on purchase type...
        Text::make('Recipient')
            ->readonly()
            ->dependsOn(
                ['type'],
                function (Text $field, NovaRequest $request, FormData $formData) {
                    if ($formData->type === 'gift') {
                        $field->hide();
                    }
                }
            ),
    ]),
```

**Comment by voidgraphics** [comment]
@stepanenko3 I can confirm that dependent fields inside of flexible layouts currently do not work. It is likely because fields within layouts have their attributes prefixed with the layout identifier behind the scenes, so when you tell it that it needs to depend on `type`, what you really mean is you need it to depend on `04765ad0f9d4b084__type`.

There's probably a way to automate that.

Thanks for testing this out!

**Comment by voidgraphics** [comment]
After some testing, it seems this is stable enough now to encourage more people to try it out. I have created the [nova-4](https://github.com/whitecube/nova-flexible-content/tree/nova-4) branch which people can reference into their `composer.json` for now, until more testing has been done by the community. 


```json
"require": {
    "whitecube/nova-flexible-content": "dev-nova-4"
}
```

The nova-4 branch will be merged into master and we will publish a new release once we're sure that everything is working smoothly, so please if you want to help us do that, give the branch a test in your projects and report back to let us know if you've encountered problems or not.

**Comment by Nyratas** [comment]
Great work @Jubeki & @voidgraphics !

**Comment by bashgeek** [comment]
Yup, tested it and working great and expected so far, thanks!

**Comment by caseydwyer** [comment]
> I can confirm that dependent fields inside of flexible layouts currently do not work. It is likely because fields within layouts have their attributes prefixed with the layout identifier behind the scenes, so when you tell it that it needs to depend on `type`, what you really mean is you need it to depend on `04765ad0f9d4b084__type`.
> 
> There's probably a way to automate that.

@voidgraphics this makes sense and seems to be inline with what I'm running into...but is that ☝ still the case? Poking around in `group.js` and didn't know if the second chunk of this `renameFields` method was supposed to allow for a "scoped" dependency, or if it's only intended (and only works) for a "global" dependency (ie, outside the scope of a Flexible field):

```js
renameFields() {
    for (var i = this.fields.length - 1; i >= 0; i--) {
        this.fields[i].attribute = this.key + '__' + this.fields[i].attribute;
        this.fields[i].validationKey = this.fields[i].attribute;

        if (this.fields[i].dependsOn) {
            console.log('oldDependsOn: ');
            console.log(this.fields[i].dependsOn);
            Object.keys(this.fields[i].dependsOn).forEach(key => {
                console.log('key: ' + key);
                this.fields[i].dependsOn[`${this.key}__${key}`] = this.fields[i].dependsOn[key];
                this.watchedFields[dependsOn] = this.fields[i].dependsOn[key]
                delete this.fields[i].dependsOn[key];
                console.log('newDependsOn: ');
                console.log(this.fields[i].dependsOn);
            });
        }
    }
}
```

Any insight on that?

**Pull request merged**
