### PR TITLE
Introduce flexible fields validation

### PR DESCRIPTION
**Pull request by mikaelpopowicz**
Allow to validate Flexible inner fields.
Fix issue #6

### CODE REVIEW

**Comment by voidgraphics** [comment]
That's a big help, a review of this is planned for early June.
Thank you!

**Comment by mikaelpopowicz** [comment]
You are welcome. Actually this PR is not complete. I'm working on nested flexible fields validation. New commits are coming soon.

**Comment by Fenestron** [comment]
Hello. How soon will this request be considered?

**Comment by Nyratas** [comment]
Hi @Fenestron,

We'll review this PR as soon as possible.

Btw, thanks @mikaelpopowicz for the commits! Please let me know if you need help or if you think the feature is ready to for review! :)

**Comment by mikaelpopowicz** [comment]
Hi @Nyratas 

You are welcome.

Yeah the feature is ready to be reviewed 🚀

**Comment by Lotfull** [comment]
Hi, @Nyratas, have you started looking at this Pull-Request? 
This feature is very useful for this package.
Thanks in advance!

**Comment by voidgraphics** [comment]
So sorry for the wait, life's a little wild at the office, but we promise we'll make time for this as soon as we can!

**Comment by cgarofalo** [comment]
Please make this PR 🙏 soon. Thanks :)

**Comment by gwleuverink** [comment]
> So sorry for the wait, life's a little wild at the office, but we promise we'll make time for this as soon as we can!

Pretty please! 🙏  Thanks in advance!

**Comment by Nyratas** [comment]
Hi everyone,

As explained in issue #6, we will not merge this PR since we have thought of a simpler way to achieve validation. We're working on its implementation as we speak, I'll keep you posted.

Thanks for submitting the draft, it gave us more insight on how to solve the issue. Keep it up! :)

Have a nice day 🌤

**Comment by Nyratas** [comment]
Update: Our version of flexible validation has been released today in v0.1.8, hope you'll like it.

It does not require adding traits or other properties to the resources including the field.

Thanks again!

**Pull request closed without merging**
