### PR TITLE
Fix existing layouts breaking as of 1.0.9

### PR DESCRIPTION
**Pull request by mabdullahsari**
#469 broke existing layouts. This PR rectifies that.

### CODE REVIEW

**Review by toonvandenbos — APPROVED** [review]

**Comment by jsmit99** [comment]
@toonvandenbos needs a tagged version I think.

**Comment by jsmit99** [comment]
Hmm alright, do you have any idea when will things be released?

**Comment by mabdullahsari** [comment]
@jsmit99 You can use a composer patch in the meantime, until a version is tagged.

**Comment by jsmit99** [comment]
Hmm but it shouldnt take to much time to create a minor release? It's not working for latest nova now.

**Comment by mabdullahsari** [comment]
@jsmit99 Use `dev-master` then until it's tagged? There are plenty of options to make it work "now".

**Comment by PieterCappelle** [comment]
Please revert this.
https://github.com/whitecube/nova-flexible-content/pull/469

**Comment by mabdullahsari** [comment]
> Please revert this. #469

Why revert this fix that fixes the defect?

**Comment by PieterCappelle** [comment]
@mabdullahsari See this issue, I'm experiencing exactly the same since this update > https://github.com/whitecube/nova-flexible-content/issues/475.

**Pull request merged**
