### PR TITLE
Allow user to pass in pre-initialized layout object to addLayout

### PR DESCRIPTION
**Pull request by chrisneal**
As well as allowing the user to pass in multiple arguments to the addLayout function, and the layout class name as a string, allow the user to pass in a single argument of a pre-initialized layout object.

### CODE REVIEW

**Comment by CraigChilds94** [comment]
+1

**Comment by voidgraphics** [comment]
Hi @chrisneal, thanks for your contributions!

I don't really have a problem with merging this, but I am kinda curious as to why you would need to create the layout instance yourself. Can you shed some light on your use case, please?

Thanks

**Comment by chrisneal** [comment]
Hey. My use case is that I need to setup the layout depending on the resource/resource type, for instance change some fields read only properties. Doing it this way would give me extra control to initialise the layouts, and made the most sense to me 😊.

**Comment by voidgraphics** [comment]
@chrisneal Fair enough! Thanks for the PR.

**Pull request merged**
