### PR TITLE
Fixed Advanced Nova Media Library compatibility

### PR DESCRIPTION
**Pull request by GarethSomers**
Hi,

I've tackled https://github.com/whitecube/nova-flexible-content/issues/64. I'm a little out of my depth so input so appreciated.

### What I've done:
- I've extended `Spatie\MediaLibrary\FileAdder\FileAdder` and `Spatie\MediaLibrary\FileAdder\FileAdderFactory` to allow a suffix on the collection name
- I've added to the new `Whitecube\NovaFlexibleContent\Concerns\HasMediaLibrary` to inject the Layout key as the suffix.
- I've modified the layout key generation on the frontend to be the appropriate format for the final key. I may be overlooking why this was done in the first place so I appreciate input
- I've added a layout option $removeCallbackMethod to enable the user to set what should happen when a layout is removed. (see usage below).

### How it works:
The suffix gets appended to the collection name before adding and grabbing from the media library, and-so differentiates between other layouts.

Then the new callback can be added to the layout to clear that media library when the layout is removed.

### Relies on:
- ~https://github.com/ebess/advanced-nova-media-library/pull/107~ Merged
- ~https://github.com/ebess/advanced-nova-media-library/pull/108/commits/6755ff812be388c96dfacffc76abf39078eb6ace~ No longer required because we're not using a ComputedField as the attribute name

### Usage:
```
<?php

namespace App\Nova\Flexible\Layouts;

use Ebess\AdvancedNovaMediaLibrary\Fields\Images;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Whitecube\NovaFlexibleContent\Concerns\HasMediaLibrary;
use Whitecube\NovaFlexibleContent\Layouts\Layout;

class FeaturedImageLayout extends Layout implements HasMedia
{
    use HasMediaLibrary;

    protected $name = 'featured_image';

    protected $title = 'Image';

    public function fields()
    {
        return [
            Images::make('Image', 'image')
        ];
    }

    /**
     * The default behaviour when removed
     *
     * @param $flexible The $flexible field
     * @param Whitecube\NovaFlexibleContent\Layout $layout The layout (should equal $this).
     */
    protected function removeCallback($flexible, $layout)
    {
        foreach ($this->getMedia('image') as $media) {
            $media->delete();
        }
    }
}

```

### CODE REVIEW

**Comment by voidgraphics** [comment]
Thanks for your work, we'll take a look at it shortly 😄

**Comment by OliverZiegler** [comment]
Not sure if this is the best way to go...

I managed using the same collection name on the same layout (and different layouts) by
* generating a custom layout
* generating a custom resolver (resolving data from a FlexibleItem Model)
* resolving the layout data from a "FelxiblIetem" table
* connecting the media to FelxibleItem instances instead of the main model

If interested I can share my code (after some refactorings 😊 )

**Comment by reinvanoyen** [comment]
> Not sure if this is the best way to go...
> 
> I managed using the same collection name on the same layout (and different layouts) by
> 
> * generating a custom layout
> * generating a custom resolver (resolving data from a FlexibleItem Model)
> * resolving the layout data from a "FelxiblIetem" table
> * connecting the media to FelxibleItem instances instead of the main model
> 
> If interested I can share my code (after some refactorings 😊 )

So basically what @GarethSomers managed to do, but without appending that layout key as suffix? If so, I think we would all be very happy if you could share your solution.

**Comment by OliverZiegler** [comment]
Ok Guys, here you go 😊 

Check out the [Gist](https://gist.github.com/OliverZiegler/48e9c6f06762a03b32a9f352d47d2799) I created.

**Comment by GarethSomers** [comment]
Hey @voidgraphics any progress on this ?

I do _somewhat_ prefer @OliverZiegler @reinvanoyen suggestion that the flexible row's could be on another table.

If that's the direction the package takes it would need a new major release and to resolve incompatibilities with previous versions.

In which case if there's no obvious problems / concerns with this PR can I suggest we it's merged and used as the solution in the meantime? 

Let me know your thoughts. Thanks guys

**Review by toonvandenbos — COMMENTED** [review]
Hi everybody,

Thanks for sharing your thoughts on this PR!

First @GarethSomers, a few questions/remarks regarding the current state of your pull request:
- I'm not sure what your changes in `resources/js/components/FormGroup.vue` have to do with the issue we are talking about here? Could you please explain?
- The idea behind the `getTemporaryUniqueKey` method is to generate a key that will identify a freshly created flexible group without requesting a truly unique key to the back-end using an unnecessary Ajax call. The key is slightly different than the final one, which is generated in the package's back-end, because we need to be able to check if the key needs to be switched to a stronger & final one.
- I like the idea of the `removeCallback` method. We'll take a further look into this feature and see how we could expose the callback for other use cases. I think that we'll need to improve its implementation a little bit, though.

Regarding the real issue, being the fact we're currently not able to link a single layout to the Media Library table, I understand the need of a table that will identify each layout group implementing the HasMedia trait. However, this is not how the package currently works and I'm not willing to push the package into a database-based direction just for this use case.

I'll take a look if we can't provide a migration that will link a layout key to a model, just for the ANML package. What are your thoughts about this?

Have a nice day!

**Comment by pleone** [comment]
Hi all,
just wondering if there's any update on this?
I tried using https://github.com/whitecube/nova-flexible-content/issues/64 solution, but appending the key on the collection name causes the custom properties to not be saved.

Not sure if i should use @OliverZiegler  way with a new table, wait for a @Nyratas 's migration or wait for a merge of this pull.
Any ideas? 

thanks for the awesome work!

**Comment by pleone** [comment]
@GarethSomers is this pr working with custom attributes? I mean. are they saved properly? 
I'm considering to fork your branch if this won't get merged  for some reason.

Thanks!

**Comment by GarethSomers** [comment]
Hi @pleone sorry I haven't tested custom attributes. I'm not currently using those features. 

Feel free to fork my fork and investigate.

**Comment by pleone** [comment]
@GarethSomers just tried, confirm attributes are working too.

Using your fork as a fallback, thanks for your idea and work!

**Comment by GarethSomers** [comment]
@pleone Great to hear. Cheers!

**Comment by cgarofalo** [comment]
@GarethSomers @Nyratas Any updates on this? I am eagerly awaiting this fix. Thanks for your work!

**Comment by GarethSomers** [comment]
Hi @cgarofalo I'm not actively working on this.

I think I'm right in saying (@Nyratas ?) there are some bigger (opinionated) changes this PR introduces which has prevented it from being merged in.

You can explicitly require this PR (or my branch) which will let you use this fix. If you do so I would recommend requiring a single release tag of Advanced Nova Media Library + Spatie Media Library.

**Comment by voidgraphics** [comment]
Thank you very, very much for this PR @GarethSomers. I finally got around to it and am merging it now. I do prefer your approach of keeping it linked to the parent model with an automatically keyed collection name rather than having the media linked directly to the layouts. That way we don't need to try to trick spatie's package into thinking that the layout is actually a model, which it is not.

I will be doing some more work on it before tagging a release later today zhich will include this and full compatibility with the new v8 version of spatie/laravel-medialibrary.

**Comment by GarethSomers** [comment]
Phew! Love it. Cheers mate!

**Comment by voidgraphics** [comment]
Included in [v0.2.1](https://github.com/whitecube/nova-flexible-content/releases/tag/v0.2.1)

**Pull request merged**
