### PR TITLE
Fix dropdown z-index

### PR DESCRIPTION
**Pull request by KasparRosin**
Seems that the dropdown z-index was broken again after this commit:
https://github.com/whitecube/nova-flexible-content/commit/1690470eb4e223a7477c44d6ae0c87bfcb438e6d#diff-936f732d109ddeebe68818f777cfef053c6e27fcdb0121122d9a6b0af61ee8b7R6

### CODE REVIEW

**Comment by KasparRosin** [comment]
Had to make some additional changes, removed unnecessary wrapper div.

**Comment by KasparRosin** [comment]
@voidgraphics Can we have this merged or some feedback?
We are receiving a lot of reports about not being able to use flexible. I would like to avoid using/maintaining a fork.

I'll add a screenshot as well, unable to click any of the buttons due them being behind the other flexible field.
image

**Comment by voidgraphics** [comment]
I will merge this and release later today

**Comment by KasparRosin** [comment]
Thanks!

**Pull request merged**
