### PR TITLE
Support DependsOn for fields in Flexible Content layouts

### LINKED ISSUE #341: dependsOn has no effect when the parent field is inside flexible
## Code example:
```
Text::make('Recipient')
    ->readonly()
    ->dependsOn(
        ['type'],
        function (Text $field, NovaRequest $request, FormData $formData) {
            if ($formData->type === 'gift') {
                $field->readonly(false)->rules(['required', 'email']);
            }
        }
    ),

Flexible::make('Content')
    ->addLayout('Simple content section', 'wysiwyg', [
        Text::make('Recipient')
            ->readonly()
            ->dependsOn(
                ['type'],
                function (Text $field, NovaRequest $request, FormData $formData) {
                    if ($formData->type === 'gift') {
                        $field->readonly(false)->rules(['required', 'email']);
                    }
                }
            ),

        Select::make('Purchase Type', 'type')
            ->options([
                'personal' => 'Personal',
                'gift' => 'Gift',
            ])
            ->default('personal'),
    ]),
```

## Field behavior:

Laravel - Create Test

P.S. Example taken from [documentation](https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields)

### PR DESCRIPTION
**Pull request by ianrobertsFF**
This PR should support DependsOn for fields within Flexible Content layouts

- It does not support Fields being dependant on fields in different groups, or vice versa
- It does not support Fields being dependant on fields outside of Flexible content
- I have tested it and can see no issues, but I am not an expert, I encourage further testing before merging
- Requires the trait HasFlexibleDependsOn in the resource

Resolves #341

### CODE REVIEW

**Comment by ianrobertsFF** [comment]
A few updates since nova made some changes, trait is also now more robust.

**Comment by voidgraphics** [comment]
Thank you, I will take a look at this soon. 👍

**Comment by stepanenko3** [comment]
Any news?

**Comment by ianrobertsFF** [comment]
@toonvandenbos I see you closed out some of the other PRs, any chance of taking a look at this one?

Thanks

**Comment by ianrobertsFF** [comment]
Let me know if this isn't going to be looked at and ill make a proper fork

Thanks

**Comment by KasparRosin** [comment]
Would love to have this get looked at @voidgraphics

**Pull request closed without merging**
