### PR TITLE
Send params for preset class

### PR DESCRIPTION
**Pull request by vlinde**
We need this change to be able to send parameters in the preset class.
This package will be used for big projects, which means we can collaborate for new improvements.
Or if we can use another method, we need to know. 

Thanks for this awesome package!

### CODE REVIEW

**Comment by vlinde** [comment]
> That works for me, but can you please update the docblock on top of it as well?

Like this?

**Comment by voidgraphics** [comment]
Thanks @vlinde 👍

**Comment by vlinde** [comment]
Can you create a new tag version or update the last one?

**Comment by voidgraphics** [comment]
@vlinde we will once we have everything tested properly. You can use `dev-master` if you need the changes urgently.

**Pull request merged**
