### PR TITLE
Respect field readonly flag

### PR DESCRIPTION
**Pull request by chrisneal**
Hide add layouts button when field is marked as readonly
Hide delete/order group buttons when field is marked as readonly

### CODE REVIEW

**Comment by CraigChilds94** [comment]
+1

**Comment by voidgraphics** [comment]
Thanks!

**Comment by chrisneal** [comment]
@voidgraphics Sorry, I realised I hadn't recompiled the assets before creating this PR. So even though this is merged, those will need to be recompiled.

**Comment by Ragash** [comment]
it seems the change has been reverted, it would be nice to have it again :)

**Pull request merged**
