### PR TITLE
L11 compatibility 

### PR DESCRIPTION
**Pull request by LTKort**
Adds Laravel 11 support in composer (issue #508).
This also reverts #490 as stated in #507 
And includes the PR #506 for issue #505 

---- 

I have not tested this on this repo, we use our own fork.
To test or use these changes, temporarily add my fork to the repositories property of your composer.json:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ltkort/nova-flexible-content.git"
        }
    ]
}
```
Then update your dependency constraint to reference this branch:
```
{
    "require": {
        "whitecube/nova-flexible-content": "dev-l11-compatibility",
    }
}
```
Finally, run: composer update

### CODE REVIEW

**Comment by voidgraphics** [comment]
Thank you! Willing to merge if a couple people can please verify, I can't do it right now

**Comment by lozobojan** [comment]
Fixed the issue for me. Thanks, @LTKort!

**Comment by harmenjanssen** [comment]
I can also confirm this fixes the issue for me!

**Comment by voidgraphics** [comment]
Tagged `v1.1.0` with this, thanks

**Pull request merged**
