### PR TITLE
Fixing file validation rules

### PR DESCRIPTION
**Pull request by michaelbaril**
Hi,
Validation rules for file attributes are not applied correctly since the name of the flexible attribute is not the actual name of the file in the request. (issues #112, #238)
This fixes the issue, hopefully.

### CODE REVIEW

**Comment by cgarofalo** [comment]
Can this be merged? Any movement on this?

**Comment by gijsbeijer** [comment]
Tested the fix and it looks like it is working for my cases.

Could this be merged?

**Comment by toonvandenbos** [comment]
Hi all, sorry for the delay. This PR is quite interesting, will give it a closer look.

**Comment by toonvandenbos** [comment]
Thanks @michaelbaril!

I did not have much time to test if this approach could be generalized to all input attributes or if it should stay file-specific. Feel free to take a look at this if you have the opportunity.

**Pull request merged**
