### PR TITLE
Fix forceFill issue

### PR DESCRIPTION
**Pull request by LorenzoSapora**
Fixes https://github.com/whitecube/nova-flexible-content/issues/468

### CODE REVIEW

**Comment by LorenzoSapora** [comment]
Based on suggestion by https://github.com/laravel/nova-issues/discussions/5650

**Comment by jsmit99** [comment]
@toonvandenbos can we merge this?

**Comment by toonvandenbos** [comment]
Yes. Thanks @LorenzoSapora !

**Comment by PieterCappelle** [comment]
No, this breaks the entire module. Please revert as soon as possible.

**Pull request merged**
