### PR TITLE
Add button to add group at position

### PR DESCRIPTION
**Pull request by manogi**
This is quite a massive PR, I guess. I think it does not include breaking changes though.
It adds buttons between groups as soon as the first group is added (see images below). The buttons become smaller then. 

I added this PR because clients find it tedious to add a group at the bottom and then move it up until it's at the right place when there are more than around 4 or 5 groups.

The PR adds an event bus for emitting the "add-group" event, as the nesting becomes deeper, as this made more sense to me than bubbling all the way up through parent components.

I am not sure if the `SearchMenu.vue` component is still used anywhere? I could not test this component, as I found no use case for it. 

I am happy to discuss and change this PR if you consider merging it.

Cheers and thanks for this plugin!

CleanShot 2020-08-10 at 22 30 11@2x
CleanShot 2020-08-10 at 22 30 22@2x
CleanShot 2020-08-10 at 22 30 31@2x

### CODE REVIEW

**Comment by manogi** [comment]
I have found this in the docs now and will test the new functionality with this component also:

```
// searchable select field
Flexible::make('Content')->menu('flexible-search-menu');
```

**Comment by manogi** [comment]
OK - I added everything needed for `SearchMenu.vue` as well.

**Comment by manogi** [comment]
If you think the buttons are too obtrusive, I could make them even smaller (this now is an existing css class in Nova core).

If you'd like I could also make this whole thing optional via a config file setting, but since your package does not publish a config file yet, I did not want to go this way before asking which way you prefer.

**Comment by voidgraphics** [comment]
Hello @manogi, thanks for the PR. I understand the problem you are facing and it is a very valid concern. However I feel that your solution is a bit heavy-handed - it clutters up the UI quite a lot, and I think we could research ways to make that less intrusive while still being discoverable. Maybe some sort of menu that only shows up when you hover around the area between two layouts?

**Comment by manogi** [comment]
Yes - I like that idea and I'd be glad to try that. Do you think the approach of a "default" but smaller button style is OK, or would you rather change that?

**Comment by manogi** [comment]
May be something more in the style of the buttons hanging on the left of the groups - grey outline, grey small text.

**Comment by Nyratas** [comment]
Hi @manogi,

Thanks for your PR, interesting feature indeed! I was writing a similar reply but @voidgraphics was faster than me. 

The UI can get a little bit messy when using multiple layers of Flexible content and I feel all these buttons (even smaller ones) will add a lot of visual noise. I think we should hide the button or UI element that reveals it until the user is hovering the area between two groups. Before implementing a new version, I'd suggest we agree on an efficient design for this new feature.

**Comment by voidgraphics** [comment]
I think the default button style is fine! Fits well with existing Nova controls.

**Comment by manogi** [comment]
I will try something locally and first just paste a PNG, GIF or MP4 here before pushing more changes.

**Comment by manogi** [comment]
This is what I implemented locally so far:

CleanShot 2020-08-13 at 13 34 53

**Comment by manogi** [comment]
I have now added the latest changes (show on hover) to the commit.

**Comment by Nyratas** [comment]
Hi @manogi,

Thanks for your time! A few questions though:

- What is the purpose of the `EventBus` file? I can see what it does, but I wonder what its advantages are compared to the previous version. Please enlighten me! :) 
- Could it be possible to enable this feature from an option on the field? I know some users won't be too pleased with this as a default behavior since they're using the field in a controlled way that does not cope well with this new feature.

**Comment by manogi** [comment]
Hi @Nyratas, I use the EventBus so that I don't have to pass down and bubble up the "addGroup" functionality through 3 layers (FormField -> FormGroup -> OriginalDropMenu).

Yes, this absolutely could be hidden behind an option. I could add this to this PR.

**Comment by manogi** [comment]
Oh man - I screwed up, I wanted to make a completely different repo by someone completely different who is not maintaining it anymore my own and ended up doing it all on your repo. I kind of lost track of this, because it has been some time I was working on this. Will undo all my changes...

**Comment by manogi** [comment]
I waited too long, too many changes since when I forked this. I will make a second try in another clean PR from current master.

**Pull request closed without merging**
