### PR TITLE
Add customizable modal for when deleting a group

### PR DESCRIPTION
**Pull request by chrisneal**
This PR adds a modal when deleting an asset, replacing the small "Delete" and "Cancel" buttons that appeared previously.

It respects the custom message/button text options.

image

### CODE REVIEW

**Comment by chrisneal** [comment]
@Nyratas I wasn't able to replicate the issue you were having on my last PR.

https://www.loom.com/share/818f80d4cbde4be48f230076bfd35ecc

**Comment by voidgraphics** [comment]
Looks good! I can see however you did not remove the code for the previous confirmation box - if you look closely you can even see it show up at the bottom of the layouts in your video. Did you intend for it to be this way? I think it would be better to get rid of it.

Thanks for the PR!

**Comment by chrisneal** [comment]
@voidgraphics Oops. my bad. All removed :)

**Comment by voidgraphics** [comment]
@Nyratas ok to merge this? Looks fine to me but was there a problem I'm not aware of?

**Comment by Nyratas** [comment]
@voidgraphics if your review is positive we can merge this PR. Please take a look at code style if you can :)

Thanks @chrisneal !

**Comment by voidgraphics** [comment]
Code style looks consistent with what we have so far 👍

**Pull request merged**
