### PR TITLE
add limit function to only allow X instances of content

### PR DESCRIPTION
**Pull request by m-triassi**
Allows for limiting the number of groups created for all layouts for any given flexible field.
Solves #3

Squashed Commits:
- fix typo in limit counter name increment on remove group
- compile js to production

### CODE REVIEW

**Comment by voidgraphics** [comment]
Very cool, however I think this is not exactly what #3 was about! 😅 

If my understanding is correct, this PR makes limited flexible fields (for example, allow 5 layout instances in total, regardless of which layouts are chosen).

#3 is about being able to add limits to each layout type separately. The feature you added is very welcome however, I just hadn't thought of it before.

Just a nitpick, could you add it to the docs as well, please?

Thanks! 👍

**Comment by m-triassi** [comment]
@voidgraphics Definitely ill add to the docs now! i'll make a second PR for limiting specific layouts in that case!

**Comment by m-triassi** [comment]
@voidgraphics Docs updated, feel free to suggest changes and such; i'll get to work on limiting specific layouts next 😄

**Comment by cgarofalo** [comment]
If this is ready to be pulled in please do so. 🙏  Thanks.

**Comment by voidgraphics** [comment]
Merged, thanks! You can start using it now by changing your version to `dev-master` if urgent, and a release will follow suit by next week once I've had time to confirm everything's running smoothly.

**Comment by cgarofalo** [comment]
@voidgraphics Thank so much. I am using dev-master for now.

**Comment by jordydevulder** [comment]
Awesome! looking forward to the release!

**Comment by royduin** [comment]
This one isn't mentioned in the release notes anywhere here: https://github.com/whitecube/nova-flexible-content/releases, it was released with 0.1.8 I think?

**Comment by voidgraphics** [comment]
@royduin Yep, forgot to add it to the notes. I updated it, it was indeed a part of 0.1.8.

**Pull request merged**
