### PR TITLE
Add confirm remove prompt when click on delete button 

### PR DESCRIPTION
**Pull request by onemoreahmad**
Add confirm remove mentioned here https://github.com/whitecube/nova-flexible-content/issues/32

Screen Shot 2019-07-09 at 8 29 34 AM
Screen Shot 2019-07-09 at 8 29 23 AM

Screen Shot 2019-07-09 at 8 30 29 AM

Screen Shot 2019-07-09 at 8 30 07 AM

### CODE REVIEW

**Comment by onemoreahmad** [comment]
I have no idea why the two commits "Fix nested images on update" and "Confirm remove prompt" comes together in one pull request, sorry I'm relatively new to the whole PR thing. Feel free to fix that if it's possible.

**Comment by voidgraphics** [comment]
Hey, thanks for this! Do you mean this PR should only include 9ff6132764dd08c9c674ee9c6dc9fe2fae865610?

**Comment by onemoreahmad** [comment]
Hey @voidgraphics, correct.

**Comment by voidgraphics** [comment]
Merged in 4b389dfb1a8cb6bfff83171a406170a0598e5d1c

**Pull request closed without merging**
