### PR TITLE
Support displayUsing() callback for fields inside a Layout

### PR DESCRIPTION
**Pull request by Tarpsvo**
Added differentiation between a regular `resolve()` and `resolveForDisplay()` calls on the `Flexible` field. Fields inside a `Layout` now call `displayUsing()` callbacks to get their proper display value on Index and Detail views.

### CODE REVIEW

**Comment by flxsource** [comment]
Would this also allow use of `displayUsingLabels()` on select fields?

**Comment by Tarpsvo** [comment]
Hey! Yes, it does. The `displayUsingLabels()` just calls `displayUsing()` and the flow works. Tested it as well.

**Comment by Lezhni** [comment]
Any news?

**Comment by voidgraphics** [comment]
Thanks!

**Comment by alejandrosanchez18** [comment]
How can I do for use displayUsingLabels() on the Flexible field. I'm trying to use this but the field display the key.

**Comment by voidgraphics** [comment]
Sorry, I don't understand your question @alejandrosanchez18

**Comment by ChrisAluani** [comment]
@voidgraphics I have the same issue as alejandro. I think what he means is, that when using the displayUsingLabels() callback on the Select field inside a Layout the key and not the value is displayed on the detail view, when **using a custom preset class**. It works otherwise (if the layout is directly added to the flexible field). This is problem is also true for all other callbacks like "hideOnDetail" etc. Is there something missing in the documentation for presets? Should I open a new issue for that?

**Comment by voidgraphics** [comment]
Thanks for the clarification, that does sound like a bug to me, so please do open a new issue 👍

**Comment by ChrisAluani** [comment]
@voidgraphics Done.

**Pull request merged**
