### PR TITLE
dropdown list pin changed

### PR DESCRIPTION
**Pull request by kaanosman**
dropdown list with many elements overflow to header problem fixed

### CODE REVIEW

**Comment by kdrmlhcn** [comment]
@whitecube @Nyratas @chrisneal @voidgraphics @vlinde @gjphenry Please merge this pull request. This is so important thing.

**Comment by chrisneal** [comment]
Would if I could @kdrmlhcn

**Comment by Nyratas** [comment]
Merged into `dev-master`. Will be shipped in next release, but not sure when that will be, sorry. In the meantime I'd suggest you use dev-master.

**Comment by bsormagec** [comment]
@Nyratas you closed my issue but i am already waiting your new release can you please release it ASAP. We are waiting your release to release our app. Thanks!

**Pull request merged**
