### PR TITLE
build: use nova-kit/nova-packages-tool to update nova assets

### LINKED ISSUE #381: Flexible field disappears when using dependsOn()
I have the following fields

```
           Text::make(__('Telephone Number'), 'tel')->rules('max:255')->nullable(),
            Flexible::make('More Information', 'more_info')->button('Add information')
            ->addLayout('Extra Info', 'wysiwyg', [
                
                Text::make(__('Telephone Number'))->rules('max:255')->nullable(),
                Email::make(__('Email'))->rules('max:255')->nullable(),
                
            ])
            ->dependsOn(
                ['tel'], 
                function (Flexible $field, NovaRequest $request, FormData $formData) {

                    if($formData->tel){

                        $field->show();
                        
                    }

                }
            ),
```

And as soon as I type something in my Text field, the Flexible field disappears

I have the latest version of Nova(4.13.0) and the Flexible package(1.0.1), 
I know this is supposed to be fixed recently according to #366  and #347 

https://user-images.githubusercontent.com/38506744/186996043-f88d0856-ddf2-48dd-b8c7-7194280556fa.mov

### PR DESCRIPTION
**Pull request by mikaelpopowicz**
From @crynobone

> * `laravel-nova` will be served via external `window.LaravelNova` and no longer requires asset rebuild whenever `mixins` contains any changes.
> * `nova-kit/nova-packages-tool` will bump new version after Nova made any minor/patch release before user can received the updated version.
> * smaller dist files since it no longer build all `mixins`.

Closes https://github.com/whitecube/nova-flexible-content/issues/381

Closes https://github.com/whitecube/nova-flexible-content/issues/356

### CODE REVIEW

**Comment by mikaelpopowicz** [comment]
Closes https://github.com/whitecube/nova-flexible-content/issues/356

**Comment by mstaack** [comment]
@voidgraphics @dinandmentink @pierrepavlov @toonvandenbos 
can we get this merged please?
currently css leaks break my nova application

**Comment by voidgraphics** [comment]
Included in `v1.0.3`, thanks @mikaelpopowicz!

**Comment by mstaack** [comment]
great! thanks

**Pull request merged**
